unicode replacements

diff --git a/run_roms b/run_roms
--- a/run_roms
+++ b/run_roms
@@ -48,7 +48,7 @@ optional arguments:
 function raise_error()
 {
 tput setaf 1
-echo "ERROR -- $1" >&2
+echo "ERROR – $1" >&2
 tput sgr0
 exit 1
 }
diff --git a/util/rif_setvar b/util/rif_setvar
--- a/util/rif_setvar
+++ b/util/rif_setvar
@@ -2,7 +2,7 @@
 
 if [ $# -lt 3 -o $# -gt 4 ]
 then
-    echo "ERROR -- Three or four input arguments required." >&2
+    echo "ERROR – Three or four input arguments required." >&2
     exit 1
 fi
 
@@ -18,18 +18,18 @@ fi
 
 if [ ! -e $infile ]
 then
-    echo "ERROR -- File \"$infile\" does not exist." >&2
+    echo "ERROR – File \"$infile\" does not exist." >&2
     exit 1
 fi
 if [ ! -f $infile ]
 then
-    echo "ERROR -- \"$infile\" is not a regular file." >&2
+    echo "ERROR – \"$infile\" is not a regular file." >&2
     exit 1
 fi
 varcheck=`grep -on "^\(\ *$varname\ *=\{1,2\}\ *\)\([^!]*[^! ]\)" $infile | wc -l`
 if [ $varcheck = 0 ]
 then
-    echo "ERROR -- Variable \"$varname\" does not exist." >&2
+    echo "ERROR – Variable \"$varname\" does not exist." >&2
     exit 1
 fi
 
