version 1.3 of run_roms_da

diff --git a/run_roms_da b/run_roms_da
--- a/run_roms_da
+++ b/run_roms_da
@@ -9,7 +9,7 @@
 #                                                                      #
 ########################################################################
 
-VERSION=1.2
+VERSION=1.3
 
 ########################################################################
 #
@@ -35,6 +35,7 @@ VERSION=1.2
 # 1.1.1     bugfixes related to changes in 1.1
 # 1.1.2     bugfix for -e/--extend option
 # 1.2       added support for "ini_file_directory" in configuration
+# 1.3       added support for "ini_file_variables" in configuration
 ########################################################################
 
 ########################################################################
@@ -730,6 +731,17 @@ if [[ -z "$ini_filetype" ]]; then
     fi
 fi
 
+# report ini_file_directory / ini_file_variables configuration
+if [[ -n "$ini_file_directory" ]]; then
+    if [[ -n "$ini_file_variables" ]]; then
+        echo " • copying variables \"$(sed "s/,/\", \"/g" <<< "$ini_file_variables")\" from files in \"${ini_file_directory}\" to the initial file at the start of each cycle"
+    else
+        echo " • using files in \"${ini_file_directory}\" as initial conditions"
+    fi
+elif [[ -n "$ini_file_variables" ]]; then
+    raise_error "Must specify configuration option \"ini_file_directory\" to set \"ini_file_variables\"."
+fi
+
 #
 # initialize other variables
 #
@@ -1048,7 +1060,7 @@ while [[ $(bc <<< "$day < $stop_day") == 1 ]]; do
 
     # initial conditions file
 
-    if [[ -n "$ini_file_directory" ]]; then
+    if [[ -n "$ini_file_directory" ]] && [[ -z "$ini_file_variables" ]]; then
         # if ini_file_directory is set in configuration, use that to source a
         # new initial file every cycle
         # if there is no initial file in ini_file_directory for the first cycle, use
@@ -1082,6 +1094,23 @@ while [[ $(bc <<< "$day < $stop_day") == 1 ]]; do
             raise_error "Cannot find initial file \"${storage_dir}/$ini_file_local\"."
         fi
         cp -p ${storage_dir}/$ini_file_local .
+    fi
+    if [[ -n "$ini_file_variables" ]]; then
+        if [[ ! -f ${ini_file_directory}/$ini_file_local ]]; then
+            # if file cannot be found in first cycle, use $ini_file
+            if [[ $(bc <<< "$day == $start_day") == 1 ]]; then
+                echo "   Cannot find file \"${ini_file_directory}/$ini_file_local\", to copy variables from (active \"ini_file_variables\" option)."
+                echo "   This is accepted in first cycle but will result in an error if no file for the next cycle is found."
+            else
+                raise_error "Cannot find file \"${ini_file_directory}/$ini_file_local\", to copy variables from (active \"ini_file_variables\" option)."
+            fi
+        else
+            echo "   copying variables \"$(sed "s/,/\", \"/g" <<< "$ini_file_variables")\" from \"${ini_file_directory}/$ini_file_local\" to current initial file"
+            ncks -A -v $ini_file_variables "${ini_file_directory}/$ini_file_local" "$ini_file_local"
+            if [[ "$?" -ne "0" ]]; then
+                raise_error "Something went wrong during ncks operation."
+            fi
+        fi
     fi
 
     # observation file
